### ISSUE TITLE
Support inverse transform

### ISSUE THREAD

**Issue by pycodev** [tkaabbc/vscode-px-transform#1]
Could support inverse transform?

Almost time I perform the transform from px to rpx, but spme time I need inverse it, for that I have to change the settings.

anyway, Thx for your nice work :)

**Comment by tkaabbc** [comment]
Hi pycodev, thanks for the issue! :)
The inverse transform feature you mentioned sounds great! I would like to check with you how it would behaves 

Suppose the configuration is as follows
```
// Config
multiplier: 0.01,
sourceUnit: px, 
targetUnit: rpx,
```

Here's what's already in place:
```css
height: 100px;  // select 100px and press Alt + z: 100px -> 1rpx
```

**The `inverse transform` feature might look like the following:**
```css
height: 1rpx; // select 1rpx and press Alt + shift + z: 1rpx -> 100px
```

**I wonder if a feature as described above would solve your problem?**

**Comment by tkaabbc** [comment]
> Could support inverse transform?
> 
> Almost time I perform the transform from px to rpx, but spme time I need inverse it, for that I have to change the settings.
> 
> anyway, Thx for your nice work :)

Hi pycodev, thanks for the issue! :)
The inverse transform feature you mentioned sounds great! I would like to check with you how it would behaves 

Suppose the configuration is as follows
```
// Config
multiplier: 0.01,
sourceUnit: px, 
targetUnit: rpx,
```

Here's what's already in place:
```css
height: 100px;  // select 100px and press Alt + z: 100px -> 1rpx
```

**The `inverse transform` feature might look like the following:**
```css
height: 1rpx; // select 1rpx and press Alt + shift + z: 1rpx -> 100px
```

**I wonder if a feature as described above would solve your problem?**

**Comment by tkaabbc** [comment]
Okay, I see, I'll try to add the feature as soon as I can.

**Comment by tkaabbc** [comment]
#2 done.
